In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.5.1'

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [4]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5])


In [5]:
# Print the type of data held by the tensor
print(x.dtype)

torch.int64


In [6]:
# Print the tensor object type
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.LongTensor


In [7]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [8]:
# Using torch.from_numpy()
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [9]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4])


In [10]:
# Using torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)


tensor([0, 1, 2, 3, 4])
